version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - netflix-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://db:27017/netflix-clone
    depends_on:
      - db
    networks:
      - netflix-network

  db:
    image: mongo:4.2
    volumes:
      - db_data:/data/db
    networks:
      - netflix-network

volumes:
  db_data:

networks:
  netflix-network:
